// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJT9XHxuqpAN9KzLxBX7k0wlNJn8q0dnk',
    appId: '1:73477779196:web:85ca1d962684aa2c41f179',
    messagingSenderId: '73477779196',
    projectId: 'bolaocopa2022-a37e2',
    authDomain: 'bolaocopa2022-a37e2.firebaseapp.com',
    storageBucket: 'bolaocopa2022-a37e2.appspot.com',
    measurementId: 'G-1FBZPQ22DQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7RCd5FqCVkjgmJQsHek8VFVghfqF5dAA',
    appId: '1:73477779196:android:31bfa0a9eb998e3e41f179',
    messagingSenderId: '73477779196',
    projectId: 'bolaocopa2022-a37e2',
    storageBucket: 'bolaocopa2022-a37e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxOnJJmfd04IHYn3M4lkBLOH8pEx6_314',
    appId: '1:73477779196:ios:2846c5c76275e8af41f179',
    messagingSenderId: '73477779196',
    projectId: 'bolaocopa2022-a37e2',
    storageBucket: 'bolaocopa2022-a37e2.appspot.com',
    iosClientId: '73477779196-glj09i4qm2uv46ab7eudnpn1qkq0op0h.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );
}
